### ISSUE TITLE
Root "response" attribute has upper case R for false responses.

### ISSUE THREAD

**Issue by rosetti** [omdbapi/OMDb-API#35] opened 2017-12-01 22:13 UTC
If I make a request that fails - e.g. because the movie was not found, or I didn't supply an API key, the response attribute inside the root tag, has an upper case R - e.g. "Response", instead of "response".

<root Response="False">
<error>Movie not found!</error>
</root>

<root response="True">
<movie ..../>
</root>

This is a bit annoying when parsing the response to check if the request was successful.

**Comment by josezulu** [comment] 2017-12-02 00:50
Is this different from other responses?
I think this api returns all properties with first letter capital.

**Comment by josezulu** [comment] 2017-12-02 00:52
I just checked, “Response” wen true too.

**Comment by rosetti** [comment] 2017-12-05 17:30
Hi Jose, 

I just double checked, and it appears the problem may only be in XML responses:

![image](https://user-images.githubusercontent.com/17036433/33621251-70ed1a3e-d9ea-11e7-8d5e-7fd8d4f30e82.png)

![image](https://user-images.githubusercontent.com/17036433/33621271-7b073e82-d9ea-11e7-881f-1fb06394f74f.png)

![image](https://user-images.githubusercontent.com/17036433/33621186-4118bac0-d9ea-11e7-9f3e-f5bcb8ae1663.png)

![image](https://user-images.githubusercontent.com/17036433/33621207-51ba0730-d9ea-11e7-9713-1ed7316e4bbb.png)

Thanks, 
Vin

**Comment by duckdoom5** [comment] 2017-12-06 18:21
Same issue: https://github.com/omdbapi/OMDb-API/issues/27

**Comment by josezulu** [comment] 2017-12-06 21:12
Hi Vin,

You are correct. My apologies, I had only looked at json responses.
I suggest "XML" be added to the title of this issue.

Best regards.

**Comment by omdbapi** [comment] 2018-01-16 17:11
Dupe of #27

**Closed as completed by omdbapi** 2018-01-16 17:11 UTC
Labels: duplicate
