### ISSUE TITLE
Search for people

### ISSUE THREAD

**Issue by vasyl-shumskyi** [omdbapi/OMDb-API#93] opened 2018-08-29 14:19 UTC
I would like to search for all movies by the certain director.  Is it possible with OMDb-API? 

For example, see following IMDB page with Stanley Kubrick works:

https://www.imdb.com/name/nm0000040/?ref_=fn_al_nm_1

Thanks

**Comment by vasyl-shumskyi** [comment] 2018-08-30 08:01
Rel #37

**Comment by omdbapi** [comment] 2018-09-04 06:58
Dupe of #37

**Closed as completed by omdbapi** 2018-09-04 06:58 UTC
Labels: duplicate
