### ISSUE TITLE
Response should show more actors.

### ISSUE THREAD

**Issue by CallumBrankin** [omdbapi/OMDb-API#70] opened 2018-05-31 15:18 UTC
Currently, the API response returns the first 4 actors listed on IMDB (Which are displayed by the order they're billed). This can be a problem because it doesn't correctly display the main characters. 

For example [The Lobster](https://www.imdb.com/title/tt3464902/?ref_=nm_knf_t1). Colin Farrell is the main character in this movie, but he's 7th on the list, thus, leaving him out of the api response returned by OMDb (www.omdbapi.com/?apikey=[apikey]&t=The+Lobster&y=2015).

The solution to this could be:

- Increase the number of actors returned by the API.

- Only include actors that do not have the default [imdb profile picture](https://m.media-amazon.com/images/G/01/imdb/images/nopicture/medium/name-2135195744._CB499558849_.png).

**Comment by grctest** [comment] 2018-06-25 18:58
Providing all actors and the crew would be awesome, 4 is quite limiting.

**Comment by omdbapi** [comment] 2018-09-07 08:00
Dupe of #42

**Closed as completed by omdbapi** 2018-09-07 08:00 UTC
Labels: duplicate
